"""changed user_id to customer_id

Revision ID: 289f7895b991
Revises: 
Create Date: 2026-08-15 16:00:52.878694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289f7895b991'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_wallet', sa.Column('customer_id', sa.Uuid(), nullable=False))
    op.drop_index('ix_user_wallet_user_id', table_name='user_wallet')
    op.create_index(op.f('ix_user_wallet_customer_id'), 'user_wallet', ['customer_id'], unique=True)
    op.drop_column('user_wallet', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_wallet', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_wallet_customer_id'), table_name='user_wallet')
    op.create_index('ix_user_wallet_user_id', 'user_wallet', ['user_id'], unique=True)
    op.drop_column('user_wallet', 'customer_id')
    # ### end Alembic commands ###
