"""changed customer and seller wallet initial_amount and current_balance data type from int to float

Revision ID: f6b1e0b36966
Revises: 289f7895b991
Create Date: 2026-09-03 12:35:39.299627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f6b1e0b36966'
down_revision: Union[str, None] = '289f7895b991'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
