CREATE DATABASE auth_db;
CREATE DATABASE inventory_db;
CREATE DATABASE order_db;
CREATE DATABASE payment_db;
CREATE DATABASE notification_db;
CREATE DATABASE search_db;
CREATE DATABASE glitchtip;
CREATE DATABASE ai_db;

ALTER ROLE rayco WITH REPLICATION;

\c ai_db
CREATE EXTENSION IF NOT EXISTS vector;