apiVersion: v2
name: cartord-k8s
description: CartOrd microservices platform
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: ai-service
    version: "0.1.0"
    repository: "file://charts/ai-service"

  - name: auth-service
    version: "0.1.0"
    repository: "file://charts/auth-service"

  - name: inventory-service
    version: "0.1.0"
    repository: "file://charts/inventory-service"

  - name: notification-service
    version: "0.1.0"
    repository: "file://charts/notification-service"

  - name: order-service
    version: "0.1.0"
    repository: "file://charts/order-service"

  - name: payment-service
    version: "0.1.0"
    repository: "file://charts/payment-service"

  - name: search-service
    version: "0.1.0"
    repository: "file://charts/search-service"

  - name: postgres
    version: "0.1.0"
    repository: "file://charts/postgres"

  - name: redis
    version: "18.x.x"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: redis.enabled

  - name: kafka
    version: "26.x.x"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: kafka.enabled

  - name: elasticsearch
    version: "8.5.1"
    repository: "https://helm.elastic.co"
    condition: elasticsearch.enabled

  - name: glitchtip
    version: "9.0.1"
    repository: "https://gitlab.com/api/v4/projects/16325141/packages/helm/stable"
    condition: glitchtip.enabled

  - name: jaeger
    version: "3.4.0"
    repository: "https://jaegertracing.github.io/helm-charts"
    condition: jaeger.enabled

  - name: opentelemetry-operator
    version: "0.124.1"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: opentelemetry-operator.enabled

  - name: opentelemetry-collector
    alias: otel-collector
    version: "0.175.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: otel-collector.enabled

  - name: prometheus
    version: "29.35.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled

  - name: grafana
    version: "13.2.7"
    repository: "https://grafana-community.github.io/helm-charts"
    condition: grafana.enabled

  - name: debezium-connect
    version: "0.1.0"
    repository: "file://charts/debezium-connect"
