apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-initdb
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  {{- range $filename, $script := .Values.initdbScripts }}
  {{ $filename }}: |
{{ $script | nindent 4 }}
  {{- end }}