apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth.yml
  - database.yml
  - elasticsearch.yml
  - HPA.yml
  - ingress.yml
  - inventory.yaml
  - notification.yml
  - order.yml
  - payment.yml
  - redis.yml
  - search.yml

images:
  - name: werayco/cartord
    newTag: latest

commonAnnotations:
  env: development
  support-contact: werayco@gmail.com